"""created column role

Revision ID: 19910bf7efab
Revises: d9b516120487
Create Date: 2024-10-01 10:05:01.380940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19910bf7efab'
down_revision = 'd9b516120487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
