"""remove role column

Revision ID: d9b516120487
Revises: 31ebb4abbefa
Create Date: 2024-09-30 16:21:34.159780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b516120487'
down_revision = '31ebb4abbefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
